sudo: required

services:
  - docker                  

before_install:            
  - docker pull opennms/asciibinder

script:
  - docker run --rm -v $(pwd):/docs opennms/asciibinder build -l debug 

after_success:      
  - cd _preview/ascii_binder/latest/; mv master.html index.html;
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
