sudo: required

services:
  - docker                  

before_install:            
  - docker pull opennms/asciibinder

script:
  - docker run --rm -v $(pwd):/docs opennms/asciibinder build -l debug 

after_success:      
  - cd _preview/ascii_binder/detached/; sudo mv master.html index.html;
  - sudo git init
  - sudo git config user.name "${GH_USER_NAME}"
  - sudo git config user.email "{GH_USER_EMAIL}"
  - sudo git add . ; sudo git commit -m "Deploy to GitHub Pages"
  - test $TRAVIS_BRANCH = "master" && sudo git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
